### ISSUE TITLE
Consistent error handling

### ISSUE THREAD

**Issue by bjpop** [bionitio-team/bionitio#12]
I think a useful contribution would be to demonstrate good error handling practices.

One thing I was thinking of is a command line argument to decide whether the program will stop if it encounters a bad input FASTA file, or whether it should continue processing the remaining files.

We should try to make the error handling and output of the different versions the same.

**Comment by tseemann** [comment]
You don't often see a `--continue-on-error` option but I can see it has a use-case. Still annoying :)

**Comment by bjpop** [comment]
It has been decided that this enhancement won't be included in the interests of avoiding too much complexity.
