### ISSUE TITLE
What is the intended semantics of the verbose flag?

### ISSUE THREAD

**Issue by bjpop** [bionitio-team/bionitio#5]
We should work this out soon. It has significant impact on the Haskell code, due to purity.

**Comment by drpowell** [comment]
I like the current perl impl:

verbose >=1 print to stderr "Processing: $file\n"
verbose >=2 print to stderr filename, seq id, length

**Comment by tseemann** [comment]
I don't want to enforce a `Biotool Purity Law of 2016`.

https://en.wikipedia.org/wiki/Reinheitsgebot

**Comment by bjpop** [comment]
I think logging is still an important missing feature.

Maybe we can have regular logging and verbose logging?
