### ISSUE TITLE
Restructure repository by splitting into separate repos

### ISSUE THREAD

**Issue by TMiguelT** [bionitio-team/bionitio#51]
Currently bionitio consists of one single repo with each language implementation inside. This has a number of disadvantages, especially:
* Commit history for each language is intermingled
* Travis tests must test every implementation every time code is changed
* Travis dependencies for each implementation must be installed in order to test a single implementation

I suggest:
* Splitting the repo into separate repositories, so that each language is in a separate repo within the project. This should be done by forking the current repo once for each language implementation, and then deleting the code not related to this implementation in order to retain the commit history.
* Retaining a separate master repo remaining for the other code, such as the boot script, licenses, test data etc. 
* Since it seems that the only data that needs to be shared between language implementation repos is the test data, this can be included in the implementation repos either by including the test data as a submodule in each language, or if preferred, the test data can be cloned from the master repo during the builds.

**Comment by bjpop** [comment]
I think this is a good idea. We will need to update the bootstrap script, but this change might actually make it simpler, which is a good thing.

**Comment by drpowell** [comment]
I'm torn on this:

 * The commit history isn't a big problem I think.  `git log` on a given implementation directory gives a clear history for that tool
* Travis is slow to test every implementation, and one broken test just has a single "failing".   I agree this is annoying
* But, I do like having all the tools obviously together in the one repo where we are more likely to keep them consistent.

So, I'm not sure - will be interested to know what others think.  Perhaps if we do go for the split repos, we could have 1 master repo that pulls in all the specific implementations and tests everything.

**Comment by TMiguelT** [comment]
I'm not sure what you mean by consistency, but if it's directory structure
or API we could probably write some tests for that in the main repository
to ensure it's not broken in the implementation repos.

I'm not certain we'd want the main repo to do too much with the
implementations though, because then we have the same problem with
installing dependencies.


On 19/10/2017 9:48 AM, "David Powell" <notifications@github.com> wrote:

I'm torn on this:

   - The commit history isn't a big problem I think. git log on a given
   implementation directory gives a clear history for that tool
   - Travis is slow to test every implementation, and one broken test just
   has a single "failing". I agree this is annoying
   - But, I do like having all the tools obviously together in the one repo
   where we are more likely to keep them consistent.

So, I'm not sure - will be interested to know what others think. Perhaps if
we do go for the split repos, we could have 1 master repo that pulls in all
the specific implementations and tests everything.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bionitio-team/bionitio/issues/51#issuecomment-337749994>,
or mute the thread

**Comment by bjpop** [comment]
I think the main advantage of splitting the repos is that it will simplify the way we use travis.

At the moment, the bootstrap process is complicated by the fact that it must generate a working travis for a newly created project. However, this is not the same as the travis for the whole bionitio project. Which makes for some pretty complex code. It also means that we have some untested travis infrastructure, which is only really needed for the purposes of bootstrapping new projects.

If we split the repos, a new project would use the same travis testing machinery as we use for the individual language implementations.

Along the lines of what @drpowell and @TMiguelT have said, I think we can have a separate "bionitio" repository whose purpose is to aggregate all the tests together. Also, as @TMiguelT mentioned we will need to be careful about sharing the testing data, but I think this is soluble.

**Comment by drpowell** [comment]
Ok, agreed.  

The argument around travis is the main point for me.   I like the idea of using bionitio to create a new tool & then getting an appropriate travis setup for just that language already done in your repo.

**Comment by bjpop** [comment]
@TMiguelT has divided the repository into language-specific repositories, and this seems to work well.

We are now using a special repository called bionitio-test which holds a test shell script and test data, mostly for travis testing.

This has been made a git submodule for all the language-specific repositories.

I have been updating the bootstrap script, and have realised that license information is needed to be shared by each language-specific repository. This allows us to choose the specific license when a new fresh repository is started from bionitio.

So how to share this license information?

We could have another submodule, called bionitio-license for this purpose, and make it operate in a similar way to bionitio-test.

Or, we could combine all the "common" stuff into one submodule, perhaps called bionitio-common, or bionitio-shared.

The latter avoids a proliferation of repositories, and is the current solution I prefer, but it does require the bionitio-test repository to be renamed.

**Comment by TMiguelT** [comment]
Can the licenses not be located in the bootstrap script repository, and copied to the projects as they are generated? Why do they need to be submodules at all? (the reason the test data is a submodule is so that the tests can run in the language repositories without using the bootstrap script/repo)

**Comment by bjpop** [comment]
Yes, that is a another good option.
I will do that.
