### ISSUE TITLE
Overview page: clarify tool use vs template tool setup

### ISSUE THREAD

**Issue by AnnaSyme** [bionitio-team/bionitio#55]
Idea for restructure of Overview page. 

After the licence section, add in: 

- How to use bionitio as a tool

    - git clone [repo URL for the language you want]
    - install as per instructions
    - run and/or modify the code

- How to make a new bioinformatics tool
(= Starting a new project from bionitio)

    - curl the boot script
    - run the boot script, specify language
    - this makes the project template folders and files
    - you will then need to install the bionitio-language script # is this correct? 
    - run and/or modify the code

Is this correct? Would this be useful? 

Seems simple now I've written it down but I was confused about this distinction for a while.

**Comment by bjpop** [comment]
Thanks @AnnaSyme.

I doubt anyone wants to use bioinitio as a real bioinformatics tool on its own. Therefore I've pushed all the "tool" details to the specific language versions.

But please feel free to reword things to make it easier to understand.

**Comment by AnnaSyme** [comment]
The latest README seems clear so I'm closing this issue.
