### ISSUE TITLE
Use -g info to project name plus `-team` rather than user or local 

### ISSUE THREAD

**Issue by lonsbio** [bionitio-team/bionitio#60]
When the -g option is used, a github name is provided so we could update  templated links
 for  `username` with project `code-review` from
```
https://github.com/code-review-team/code-review
```
to 
```
https://github.com/username/code-review
```

**Comment by bjpop** [comment]
Thanks @lonsbio.

This is a duplicate of https://github.com/bionitio-team/bionitio/issues/58

 I will close this one and add your comment
