### ISSUE TITLE
Functional tests missing with `git clone`

### ISSUE THREAD

**Issue by lonsbio** [bionitio-team/bionitio#61]
A user using a plain clone (git or http address), will be missing functional tests content without a `--recurse-submodules` option. None of the README seem to mention this option. If we are encouraging the boot script this should be fine, but if we need add in `git clone` instructions as per issue #53 from @AnnaSyme  then we should add this to it.

**Comment by AnnaSyme** [comment]
Added to wiki https://github.com/bionitio-team/bionitio/wiki/How-to-modify-the-bionitio-project
