### ISSUE TITLE
URL in setup.py points to bjpop GitHub

### ISSUE THREAD

**Issue by hdashnow** [bionitio-team/bionitio#69]
After creating a new python project with bionitio my `setup.py` contains:

```url='https://github.com/bjpop/biodemo',```

Is this intended behaviour?

Command run:
```
URL=https://raw.githubusercontent.com/bionitio-team/bionitio/master/boot/bionitio-boot.sh
curl -sSf $URL | bash -s -- -i python -n biodemo -a 'Harriet Dashnow' -e h.dashnow@gmail.com -g hdashnow
```

**Comment by bjpop** [comment]
Resolved in 6779cd847f6395c924a2c59c91a472f24dfaa0b0 and e2a71140862e9d3528a9546eb771e60f5753e94f
