### ISSUE TITLE
Can we add some logging to the program?

### ISSUE THREAD

**Issue by bjpop** [bionitio-team/bionitio#9]
I think it would be nice to demonstrate logging as well.

Almost all my bioinf programs have optional logging to a file.

**Comment by tseemann** [comment]
Should this supplant the `stderr` logging?  ie. `--quiet` mode.

**Comment by bjpop** [comment]
Not sure what you mean by --quiet mode

**Comment by bjpop** [comment]
Logging has been implemented in all languages.
